version: '2.3'

services:
  minio: # => http://localhost:9000/
    image: minio/minio
    hostname: minio
    ports:
      - 9000:9000
    volumes:
      - ./data.tmp:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: password
    command: server /data
